### ISSUE TITLE
Update ReadMe

### ISSUE THREAD

**Issue by Unmoon** [amPerl/RiceEmu#1]
Update ReadMe to include information about the status of the project, how to contribute, if there is an IRC channel or communication platform etc.

**Comment by Monkey-3** [comment]
YO
HOW DO YOU GET THIS WORKING???
Keeps sayin Cant connect to any of the specified MySQL Databeses. IDK HOW TO SOLVE THAT
(And believe me, IVE TRIED MOST THINGS (EVEN LMGTFY.COM)

Plz help ya

**Comment by amPerl** [comment]
Updated README.
You need to set up a MySQL database, create tables using the schema provided and configure Rice to connect to it. Should you fail to do so, this project will be of no use to you anyway.

Closed.

**Comment by Monkey-3** [comment]
tks man
